# Generated by Django 4.2 on 2023-04-22 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzeria',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='email',
            field=models.EmailField(blank=True, max_length=245),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='logo_image',
            field=models.ImageField(blank=True, default='pizzariaImages/pizzalogo.png', upload_to='pizzariaImages'),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\1?\\d{9,10}$')]),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='website',
            field=models.URLField(blank=True, max_length=420),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='zip_code',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
