# Generated by Django 4.2 on 2023-04-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_pizzeria_active_pizzeria_description_pizzeria_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzeria',
            name='city',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
